# Generated by Django 2.2.11 on 2020-03-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_link',
            field=models.CharField(default='https://themes.3rdwavemedia.com/demo/devblog/assets/images/blog/blog-post-thumb-8.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
